### ISSUE TITLE
update with new emojis

### ISSUE THREAD

**Issue by wtquin** [Magisk-Modules-Alt-Repo/ttf-twemoji#3]
Any chance of updating this module with the new Fedora package release?
https://koji.fedoraproject.org/koji/packageinfo?packageID=26306

**Comment by ez-me** [comment]
Sorry for late reply, it's just that Twitter hasn't released an Emoji 15 version of their twemoji set, so this module is stuck at Emoji 14 untill they update.

Also this module _is_ up-to-date with the Fedora packages, because their build bot is doing Mass Rebuils (See https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild ), so the actual content hasn't changed.

When https://github.com/twitter/twemoji/ updates, only then will Fedora (and this module) have a proper update.

**Comment by ez-me** [comment]
Actually checking upstream, it may seem as this module will be dead in the long run

https://github.com/twitter/twemoji/issues/570

:crying_cat_face:

**Comment by Mokura** [comment]
It looks like Twemoji got forked from Twitter's repo by the folks that used to work on it (so it's a passion project now) - might just need to compile that into the necessary font format.

https://github.com/jdecked/twemoji

**Comment by ez-me** [comment]
[jdecked/twemoji](https://github.com/jdecked/twemoji/) updated to [Emoji 15](https://github.com/jdecked/twemoji/issues/8) and so I updated the module.

Closing for now, even tho Emoji 15.1 is already out, but it's not widely supported yet.
